[build]
  publish = "public" # Onde seus arquivos estáticos (index.html, css, js) estão
  command = "echo 'No build command needed for static site'" # Comando de build para o site principal (se houver)

[functions]
  directory = "netlify/functions" # Onde suas funções estão localizadas
  node_bundler = "esbuild" # Usar esbuild para empacotar as funções (mais rápido e eficiente)

[[plugins]]
package = "@netlify/plugin-functions-install-core"